apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synapse
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - sealedsecret.yaml
  - images.yaml
commonLabels:
  app.kubernetes.io/component: mautrix-discord
images:
  - name: dock.mau.dev/mautrix/discord
    newTag: v0.6.0 # {"$imagepolicy": "synapse:mautrix-discord:tag"}
