---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: synapse
spec:
  image: matrixdotorg/synapse
  interval: 1h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: synapse
spec:
  imageRepositoryRef:
    name: synapse
  policy:
    semver:
      range: v1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: sliding-sync
spec:
  image: matrixdotorg/synapse
  interval: 1h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: synapse
spec:
  imageRepositoryRef:
    name: synapse
  policy:
    semver:
      range: v0.x.x
