---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-synapse
  namespace: synapse
spec:
  encryptedData:
    config.yaml: AgAVw8ZYhiFFXSqKjhLrbUoWhZuXFII4uy8Tj+UhG/42hxjmsNphqw9tUxlCsFXGrvZx4/iWk7C0TD3PJJIMiEiSbsum06+Cf91ppFDVduBbF71L2CCJi/aLMfNRzfXx/Zxhs3WZWRCzFP9vTnIxFGlr+38oh/Cy2oYgrXEOdphc3dQ4dAcWoLH6IdhUwUhzKwkWNRqDXV9A0efVgxHeHatkhCWFp5Dt7KuZq0EmRAwY/yKwDjywdpuwC0cfeeLZLTurNw3Daq23wk4jwb43PuA1ovsH3140OtSIwrGpLdZzf4RYfMqKSU3kxJRYTowxaG56QxW5JxWuojuh1FSRCYN6LZopzcQmkmcehSHWlLurgFT/WrHrh8Gm1JGgoPmu4nx3GOWy7OVPcav2HGq1qtKfTlrG5G8wxZBiL6K1OTkIWC+eYdfL577xqo6iht734ff8vj1XL8QsUuG/ez0ZhNpmuqj0qq1XY0dfhkvDVu+8YBpVdt7YPEPf0eX/9m8n0cmDw8NJWDFwwKGO5ppoVHgTZPb3Xaunc5w0oMVQPWFdWFD26fufa8UTKL0SC3cskfqPXLyKZUDANzurk/wL6cuBHTKXlsLSCsaL/prSztOqbf/hbj7TnonSDhRbFBe1jaskCpiVKsp0nPE8wpuonDosqL1gjsMTA+M4CZ31OMhfF8ct7gBTZQVcKy26LH5vdHlf5G1sN/4fQDMMl9cwJcuKx+SHfeo/2/xhUfpUMHnTzE/U+J92S5sJR4UGk6G2Fd8+m+5wIyfSWhhn8B6lEabTqNEiXOKKxtiqGCpxaw3pnaBzwfI9H9piDJvK9ZCa6fJwZpR32lU5m7SnMzLtzg2gaX5o36GWp5xFaPEx5NXzlKNrl2pOpChK1iyVLi6tNmhZp+WWcKBparx6UnY9n1YKjKRXwVp3yoxXOTtQYQGtVnG2OF/Kjj18vVmoWBK4lFb0Dcjan/qXEsbOYaqhl/Iml2dqz5Zp/8QDfgpf4FIx5AQajbTpH1aKaNwRR91exjB9vWHB08xXcyS+4lMH+ypYUMHknBrrAG9+QYAxXIAFppxHq/i1yz+QFJlRKUtJxqe/aPY2LlTITI5IYQCom3OIP5sDSXMpUUOVOAVzz/Od/VkHYV91+dcmbx4Lb/+7GmisM8/KKc5xAn4zTM29pSFGU3xXYpzfJkzfU1sC6vOuJteTDMS4CRqcGBPn3Vqg1MRdD3fFvkBuydrokYWj2nhaTMZwAfHHsYRWwHz4EOFbrUpPqx3HoCKXAIPhg3bTWNCcEC9g25k9Y40aSCZWS99ebgMqLnzIIgQoYeTobWn23VCJ2V4YRr8iSEH8ONfRyqfDevS0/FO9ZFWdBr7+fUFrwJsOYnDqCfLc1aj0lBOzQNyOD4mm3PGadmNjhILLO9waLSVXO6baWJwA0b+mruWM5TaYKH2L8917993kvx4D5Fz8LUyeFGPtnHNnhmBAXicdciY8Uuyl8AD4av86vD/vf9x9Uaclt7k6me8WnVta43yVLW53lUb/400BqzE4tGeKL4AV74ZH/LpRAHOON2KJ5w7hKIGQjSLyYL3jDXX3vNjIr1yQnK8HeMW/IDjfUQ0mBfjY7ExAtS0k7SYQ5Yj02xSMHzzx4RIn4EejPFmz5xCXeg==
  template:
    metadata:
      name: matrix-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-synapse-signingkey
  namespace: synapse
spec:
  encryptedData:
    signing.key: AgA7ndjywmYQLq1J4wo/N/+oCruIP+EtQNKZyGrU2tluEIOf7wsVW0V4W0US/07K5Uc9yv19cnWjDGg/fuw2SNZ+/E6XpyPW5LH6UANDPCRjxrKd+ufvVmPeqNJtqLkEHGTM13/JcVzSqWAADPXd9f6YlNKzTq9FWH/lMxV0UZucud+IAWN2Ksv6QVbd2bdattauYORGWOGjBUyeFh270EOkf/DuWZslSTPQ4JH5wH0Odhpl+6AMYOV3r1NBtFcAdcQ8HrYLk4W+YeFWTj7Z7glHaRrypbRHJicJH5DCUB7knQVjD4ujtee1z+RU2JfzI9G+WhosOnszEWB0gTAkfCzllzQVNmnZrz+LNC7BPMk0pMjeG6e+YIn47dxXpqxborxhr99Fy6nINNXWGtYVY7IKRp7CgQ7Z6sV4rtjEmik4KdpJexDm4CNadChH/6zwgIh1DVMK0RUu14xNtmtHWVm063z5RFNNLJSLn4+pxXM2mDPBk8FL7kPfE+dbKpN1ly9XhCvrs+l5abjGb67UR3FJLfbrOA0nzuUwpNlYe0xhNuNeght4UZhY7RbIaFEXzo7Rmo6QjCFzrTSBwFIjvPRMkO5z0ZhCkuL+tBR7g1Ig7CgVj/KqsZG0GK9dx6F3X9zc16BGeS2rgjprMjT8yNwEJ1Hu4y28bOwSjO4Fk8obPH9FCg8CFfWbUIXCuxGrkCoWHm6abTUZy0ciYymvqsjPYFPsOhdBvhOIYOb4MJl4iuGZQiB5CL6TJ2MqBdOcuoPZnsfXiFOxMKpbAQ==
    signing.old.key: AgA/8IDS5TeKURn/z+T+WB0ZeITte3VQArZf0c4Fw6g+n2nupWJ/Eehfdf5ELkpdgf0unaUoIWeAbG9JAxtuDovPY3DY20K1z6u4NnJJ7KHlPepL6PD3/yI9s+R5DhSoItTbGkG7AJBHh6p2JjQjadadsb0mZm0nqaUfWRs/8BGNTUmg3kwXvSMY0LcFkZv1mvIK/1KxNOfML+380YmUw7plYHUV8h4qvtN/2j4WpOMNFTz5lsh3djetxhyfpPztRcoB6hLq1uHZ1eC0fOsf4OHcop4cBKJP4uxt/vg12/78A9nwpwsBIF3wS7PGSZrdLwLyqnqGLUv4P0XeTff/Pc3bs91cc0H6eKaf91qVlV5NFPz5cQSdmcWHhhIkl1Uoth2aFA/8dj8YkadXrT3I+QQxMI8jRC8gNF4JQFEp2BCY8qnd1BXFdy62k6l4OGMaiJyOomEE4cgO4MJL5GTHyKohu03jiWMqzZejAHF7YpGP9BiQPuVPCBbhwlaKVtWwHf6Fg8p6pOclF0RPaUHi24KDW8k+IflOn1qWGGH7VNP1+hAEIgVG+s/O0lnxRBHkClsMpXzdKp+4R30/gvFGiSZ/jcuYY0ombonPfxgCUrbvcI4ifJksUuLsHe2sJcw5IthndlMy5uGitf8p+/AGOqU/3P99jqOASML5HOvOWs72IUbdLv7Mfa+bzobB5B7eGnyUSI4oYnYjHeTjbfaOWJ3Mw9jbhxCtLUgADsXeBse5kROTr3kdjrGSKQ6u+fIV2qVeQ6mXAy7e1vCfmA==
  template:
    metadata:
      name: matrix-synapse-signingkey
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: synapse
spec:
  encryptedData:
    password: AgBem6DKMTKDuwJVNW6rBrk1Zu3shskimRzHtmQxPxscd9PwnhVoXndJlVQlFtPpcZEzDCfXvMTvAQq9RmVJ2U9O6pkvz+gY0NRhchlHFXSJ27p/FGBHhpQA2A2yfR6BnxTeHyqC0D4NjEd/7esVYsM3vkRhtq1Ry9NBpM5t4JYL4Gx3TTlnnEbytjClrHjDA4eQCgTtNyWljpnToDLTrnwWK1YZqmuE7sDzXwyh+YbSpq1+Vco2WRhpcwjALZEDz+hB7fDkAvb+zIeaRbodFnJ7xv9MXJgDADohIMbGK4KH/4BD7Mzp4Y81DrBiAIkFynQpP+HILsocTYvQrktfDR4lziDSZoIgpA7/TUK+gLkHQg1a6vngZjtDNDzs/FC2AtG2Qg/zpz3076S/57rh2MiUBLvwjExKU0p+t+kuAzfOMyEhk77k/uWBqq/fhhJZx12kR/vUoxABTfKxNAhM6KaGQj0829tqVoYfb0VL3SvD4F+DPtWTmZ5X6sjM68M389I8SWu81REsO1NWOeD5o8RF0Tly9KL1551alO3oNB21L9Q07yTlU6cUwhBJHGAEPhPV0Ll1F6hHzBSq46CqBToSqdM7oIMSSoBS0kBlZUjGUoL84pxyKE82eUUY4BkdJcWNx6srWvRgIZnUV71RYE/qwMlY2hrysbGzdH5Rcy5Xf0pGGJXc8ts5JrOXS3bozTz8+CJlX4/urIIPzH0=
  template:
    metadata:
      name: redis-password
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgAax4Hy66NvHGz+qcAE3IL7X7AtdCbzQPvvYRifaoZ6Jm84fS6AKZay3nLh7gTv56DFkfRYJusdZ2RAEK4L7w5iEWFYTdPWrK9mERDBH4dotMXwxchA/rpzqup8n4s9f/76f4qp+tKus2yTaGsBPU/iECQDCKeBzraJIFkBOxwxa/Xwp5lh2worhxxA2NuUC7lcTyf9auGkjLDkExO60EV4HxjxLoMXmBNuk/FzmCt8bCKms0DhzLyTxFx4bblgI1fkGekxhJevEv9NstH5w4BWAY/+Q0mqSYitkOt7qW6PpUL+DC67gOM5xzFpMtDflsGNF876Zd+3n0FauGPyLxfXGpeL3RcSwanN3+nfWUx/C6/hNlXjIdjPC9HQ9JBW5gyy+OlPSnt91jFwJg1HI8T0LYNSEUljSrd9TG7nue3cNQ3wu3Kcg7zqOyLnL/cw8QJbxjD008xFI/8cqqFzStJsrb/3jmOsVQgNCAR5D+thkFmjFcYT11Fhxw7D0E29Pg+DTJBythnWY3uud51FglPP+ssDCAYd0RcGXSy8Ve9i6rzy1d7Mo4Wkcnz66SjwmlQaob+wdyon+9VLumJMM0l0IH9Wyb9BqAd+wVnqtlWDSaxzyTUbK5DChIpKK2yfv6YKo5aOIxZpQ/CYMGIjGX74V9+UdScuhSYRIMNXdzY+F+lkZibX8t+2g6R3EGLC1fD7D+oM2Q/PszSFKOE=
  template:
    metadata:
      name: postgres-synapse
      namespace: synapse
    type: Opaque
