apiVersion: monitoring.coreos.com/v1
kind: PotMonitor
metadata:
  name: synapse
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: matrix-synapse
      app.kubernetes.io/instance: matrix-synapse
  podMetricsEndpoints:
    - port: metrics
      path: /_synapse/metrics
