apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: synapse
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: matrix-synapse
      app.kubernetes.io/instance: matrix-synapse
  podMetricsEndpoints:
    - port: metrics
      path: /_synapse/metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: job
