apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: synapse
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: matrix-synapse
      app.kubernetes.io/instance: matrix-synapse
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      path: /_synapse/metrics
