---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: synapse-media
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/media/data/synapse
    server: 192.168.1.100
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs
