apiVersion: v1
stringData:
  mautrix-discord.yaml: |
    as_token: c75d433b-99b5-59a7-bb23-e640301349e9
    de.sorunome.msc2409.push_ephemeral: true
    hs_token: 7d297d14-7c30-5923-8c02-30991b4f7e33
    id: discord
    namespaces:
      users:
        - exclusive: true
          regex: ^@discord_[0-9]+:seymour\.family$
        - exclusive: true
          regex: ^@discordbot:seymour\.family$
    rate_limited: false
    sender_localpart: _bot_discordbot
    url: http://mautrix-discord
  mautrix-signal.yaml: |
    url: http://mautrix-signal
    as_token: 358b906b-fc23-5bf1-ae3a-daeaf1b4b146
    hs_token: d82754a1-3f94-5880-b427-d317ad900cf3
    id: signal
    sender_localpart: _bot_signalbot
    de.sorunome.msc2409.push_ephemeral: true
    rate_limited: false
    namespaces:
      aliases:
        - exclusive: true
          regex: ^#signal_.+:seymour\.family$
      users:
        - exclusive: true
          regex: ^@signal_.+:seymour\.family$
        - exclusive: true
          regex: ^@signalbot:seymour\.family$
  mautrix-telegram.yaml: |
    url: http://mautrix-telegram
    as_token: 830e956c-ae59-539e-badb-e83ec3d19555
    hs_token: abf000ed-15bb-5133-b6e6-21a07b9abc9d
    de.sorunome.msc2409.push_ephemeral: true
    id: telegram
    sender_localpart: _bot_telegrambot
    rate_limited: false
    namespaces:
      aliases:
        - exclusive: true
          regex: ^#telegram_.+:seymour\.family$
      users:
        - exclusive: true
          regex: ^@telegram_.+:seymour\.family$
        - exclusive: true
          regex: ^@telegrambot:seymour\.family$
  mx-puppet-groupme.yaml: |
    as_token: dc14d9d8-1ff8-536f-b7c1-c6cdcf474dab
    de.sorunome.msc2409.push_ephemeral: true
    hs_token: 24443b7a-b231-5625-b5c1-dfd7e0940f31
    id: groupme-puppet
    namespaces:
      aliases:
        - exclusive: true
          regex: '#_groupmepuppet_.*:seymour\.family'
      rooms: []
      users:
        - exclusive: true
          regex: '@_groupmepuppet_.*:seymour\.family'
    protocols: []
    rate_limited: false
    sender_localpart: _groupmepuppet_bot
    url: http://mx-puppet-groupme
kind: Secret
metadata:
  name: appservice-registrations
  namespace: synapse
