apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synapse
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - sealedsecret.yaml
commonLabels:
  app.kubernetes.io/name: mx-puppet-groupme
  app.kubernetes.io/managed-by: kustomize
