---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: mautrix-telegram
spec:
  image: dock.mau.dev/mautrix/telegram
  interval: 1h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: mautrix-telegram
spec:
  imageRepositoryRef:
    name: mautrix-telegram
  policy:
    semver:
      range: v0.x.x
