apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - cert-manager
  - flux-system
  - immich
  - matrix-bridges
  - nfs-csi
  - plex
  - postgres
  - redis
  - sealed-secrets
  - synapse
