---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://nextcloud.github.io/helm/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://immich-app.github.io/immich-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://mojo2600.github.io/pihole-kubernetes/
