---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: plex
  namespace: plex
spec:
  image: plexinc/pms-docker
  interval: 1h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: plex
  namespace: plex
spec:
  imageRepositoryRef:
    name: plex
  filterTags:
    pattern: '^(?P<version>[0-9]+.[0-9]+.[0-9]+).[0-9]+-[a-z0-9]+$'
    extract: '$version'
  policy:
    semver:
      range: 1.x.x
