apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
resources:
  - deployment.yaml
  - ingress.yaml
  - pv.yaml
  - service.yaml
  - rbac.yaml
  - images.yaml
  - updateautomation.yaml
images:
  - name: plexinc/pms-docker
    newTag: 1.32.0.6973-a787c5a8e # {"$imagepolicy": "plex:plex:tag"}
