apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
resources:
  - deployment.yaml
  - ingress.yaml
  - pv.yaml
  - service.yaml
  - rbac.yaml
  - images.yaml
  - updateautomation.yaml
images:
  - name: plexinc/pms-docker
    newTag: 1.31.1.6782-77dfff442 # {"$imagepolicy": "plex:plex:tag"}
