apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  namespace: plex
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/media/data/media
    server: 192.168.1.100
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
  namespace: plex
spec:
  accessModes:
    - "ReadOnlyMany"
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-data
  namespace: plex
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  iscsi:
    targetPortal: 192.168.1.100:3260
    iqn: iqn.2005-10.org.freenas.ctl:k3s-plex
    lun: 0
    fsType: ext4
    chapAuthSession: false
