apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-operator-admission-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-operator-admission-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-operator-admission-webhook
    spec:
      containers:
        - args:
            - --web.enable-tls=true
            - --web.cert-file=/etc/tls/private/tls.crt
            - --web.key-file=/etc/tls/private/tls.key
          image: quay.io/prometheus-operator/admission-webhook:v0.63.0
          name: prometheus-operator-admission-webhook
          ports:
            - containerPort: 8443
              name: https
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/tls/private
              name: tls-certificates
              readOnly: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator-admission-webhook
      volumes:
        - name: tls-certificates
          secret:
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
            secretName: admission-webhook-certs
