---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-admission-webhook
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: prometheus-operator-admission-webhook
