apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-k8s
spec:
  endpoints:
    - interval: 30s
      port: web
    - interval: 30s
      port: reloader-web
  selector:
    matchLabels:
      operated-prometheus: "true"
