worker_app: "synapse.app.appservice"

worker_main_http_uri: http://matrix-synapse:8008
worker_replication_host: "matrix-synapse-replication"
worker_replication_http_port: 9093

worker_listeners:
  - port: 9090
    tls: false
    bind_addresses: ["::"]
    type: http

    resources:
      - names: [metrics]
        compress: false

worker_log_config: /data/config/server/log.yaml
enable_metrics: true
