## Server ##

server_name: "seymour.family"
public_baseurl: "https://matrix.seymour.family"
pid_file: /homeserver.pid
web_client: false
soft_file_limit: 0
log_config: "/data/config/server/log.yaml"
report_stats: false

## Ports ##

listeners:
  - port: 8008
    tls: false
    bind_addresses: ["::"]
    type: http
    x_forwarded: true

    resources:
      - names: [client, federation]
        compress: false

  - port: 9090
    tls: false
    bind_addresses: ["::"]
    type: http

    resources:
      - names: [metrics]
        compress: false

  - port: 9093
    tls: false
    bind_addresses: ["::"]
    type: http

    resources:
      - names: [replication]
        compress: false

## Files ##

media_store_path: "/data/media"
uploads_path: "/data/uploads"

## Registration ##

enable_registration: true

## Metrics ###

enable_metrics: true

## Signing Keys ##

signing_key_path: "/data/keys/signing.key"

# The trusted servers to download signing keys from.
trusted_key_servers:
  - server_name: matrix.org

## Extra config ##
enable_registration_without_verification: true
app_service_config_files:
  - /data/appservices/mautrix-signal.yaml
  - /data/appservices/mautrix-telegram.yaml
  - /data/appservices/mautrix-discord.yaml
  - /data/appservices/mx-puppet-groupme.yaml
suppress_key_server_warning: true
url_preview_enabled: true
url_preview_ip_range_blacklist:
  - 192.168.0.0/16
  - 172.16.0.0/12
  - 10.0.0.0/8

experimental_features:
  msc2659_enabled: true