apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synapse
resources:
  - images.yaml
  - cronjob.yaml
images:
  - name: ghcr.io/thefirstofthe300/rust-synapse-compress-state
    newTag: v0.1.4 # {"$imagepolicy": "synapse:state-compressor:tag"}
