apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 1m
  chart:
    spec:
      chart: nextcloud
      version: "3.5.4"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: nextcloud-values
  values:
    image:
      flavor: apache
      tag: 26.0.4 # {"$imagepolicy": "nextcloud:nextcloud:tag"}
    nextcloud:
      host: cloud.seymour.family
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.0.0.0/8',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
            'default_phone_region' => '+1'
          );
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 4Gi
    ingress:
      enabled: true
      ingressClass: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.middlewares: nextcloud-dav-redirect@kubernetescrd,nextcloud-webfinger-redirect@kubernetescrd,nextcloud-nodeinfo-redirect@kubernetescrd,nextcloud-no-robots@kubernetescrd
      tls:
        - hosts:
            - cloud.seymour.family
          secretName: nextcloud-tls
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgresql-hl.postgres:5432
    cronjob:
      enabled: true
    persistence:
      enabled: true
      existingClaim: data
    phpClientHttpsFix:
      enabled: true
