---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: nextcloud
spec:
  image: nextcloud
  interval: 1h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: nextcloud
spec:
  imageRepositoryRef:
    name: nextcloud
  policy:
    semver:
      range: 26.x.x
