apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-values
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgCyJVwup1eIedyrE6Y38l9rBEYhPaXJF6rKGtlZQ/YA3ZQy0lhOIixVGoEMsKl/tRbSHvKP9/c9ALek+jIXMeB/I3rB4QywjznN/3Pu63zXJGskMA3zL7r1ub+XhPzHDx4CCiDWWOKTsZ8eahVzrVZw6Eqq4e6aP/8+yTNQ8jtvhJaonhxuFyVaiEkTZncTen9dfib7ZYBsbgZVyk3M2uB8DQPQduZxklEkkadEOQeOb4pdt5u5z4f6PmL9M7htqjWYs+S9Efc9u5FMV0XvQi3dq7gl9rytv5Xr42y9wRE1IZm0EvF1/3LC58GHLIHES+OxebIDtLN8vuzpQMXPcPbI/sQud+dDTlHXA+NCMSsjv2SqK26vl9LcVc7TrBLypwrbyf2kVSghRtleqdbYvxQ82kPCLtwLYj+6RFgpn2a+1IzgGL61ZFbPhu1pSM+fvYCSPK1qgPkA41HB0sCQEcBBEP9LUZb4eLNNEY1QzmEsm4O9y5hCDFlvjDDJUipIUXlZQg0lPj+oySrpzO3EXm2IYRG6QaOTl8DFBnoD9xzw5qXHPMZyyzM0JmlNHzfA9R2x4vhMmq+Yn1eXp7fsgXBgs7H8onAKafpPKyMmHCDrjlmWs4Atay1GJQWRmLfETFWbC5B/ZDvvhsLu5MOaLcFseb6ZMrhNwxztdaTSEcz53UzJIDqAfUse8+UJ37TKP4Q008Hg00v6MNU/K+wLZu3V6iVU/+cKJAaqpKPvMY2wIosSzaTtk34i2H+B3NvWBolSb3s=
  template:
    metadata:
      name: nextcloud-values
      namespace: nextcloud
    type: Opaque

