resources:
  - microservices-deployment.yaml
  - microservices-service.yaml
  - ml-deployment.yaml
  - ml-service.yaml
  - sealedsecrets.yaml
  - pvc.yaml
  - server-deployment.yaml
  - server-service.yaml
  - server-ingress.yaml
  - web-deployment.yaml
  - web-ingress.yaml
  - web-service.yaml
  - imageupdates.yaml
images:
  - name: altran1502/immich-server
    newTag: v1.40.0_63-dev # {"$imagepolicy": "immich:immich-server:tag"}
  - name: altran1502/immich-machine-learning
    newTag: v1.39.0_61-dev # {"$imagepolicy": "immich:immich-machine-learning:tag"}
  - name: altran1502/immich-web
    newTag: v1.40.0_63-dev # {"$imagepolicy": "immich:immich-web:tag"}
