apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: machine-learning
      app.kubernetes.io/instance: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: machine-learning
        app.kubernetes.io/instance: immich
    spec:
      containers:
        - name: machine-learning
          image: altran1502/immich-machine-learning
          env:
            - name: NODE_ENV
              value: production
            - name: DB_HOSTNAME
              value: postgresql-hl.postgres.svc
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-creds
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-creds
            - name: DB_DATABASE_NAME
              value: immich
          ports:
            - containerPort: 3003
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: upload
            - name: cache
              mountPath: /cache
      serviceAccountName: immich-machine-learning
      volumes:
        - name: upload
          persistentVolumeClaim:
            claimName: immich-upload
        - name: cache
          emptyDir: {}
