apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgBY4hSnbe/jzEDlEDGLtJjiaiXShpEweAssJ/3Qu+arU2Rd6t33qbU7cbRfgwT1SawKzlNid08u5q+ie43+vKdjVyxeHuB8t5xCwdNTZvA6yrrkVLXtX6thQrAeFsjh+eQKIJgDEGS//gaCsZQHpozv1yzD+MBGNmjmHK3OKkPGW1VEhPqTKvqF42vdjRcZlZ0SUF8rBiMaw3r6oE8bsjygZFXCLgxVv0xkBQFqrDgdlP0O0EFnMDk4//cHAft7bt8lNtsL9vAAsPAEuK3PfzoANPyha98qZDa+B4/bVmsg+eR2OcOBEWQAgjc+wnZxyXS2juOBV2Y566uA5iKTCr0CcysOjK8K8dr3OmpEhJCmqSv2ibA2DKXBKeynDOJM4K0ltmA7AhdlzLFCh1kdiAEyX1C8x9qeLICXej63LgohWY33VRluzG/tytHJkcA+XtDLgTibXAAKHiseQTh14FLfJT3cWRVWdX+UTt/DDPPL7VokZsQBI4ALvU5+YbASyc9A5/OwyNt2a8tWCaeQdxyL+ce6NbV4zygqejLEeJAb7Tim3nn+niXGiAbLNyLTVa1QqCLzc/k0dM5K5leAEX3tZ3M3/n+tH2PDOEKIPNELJ20G3EXoqjvQrDkX/YRBfJWeqYCR+9xaEg0xKi7izVV4Y6lh+VHV8lVbpxk6Xlmz6UpTXwmLe/1Kg4rrAT65YeekHYzhVEKHqg1T4HN7UUBOKMV2QwP+4IabB46/ppcsGl6S/VSyJ1U8RjKK9F+aAetUdmp8HVJzlAcmUn4bIoKJtMsGd5rfgfzKwK4L1bQHg7SfVNEl9FtG635Rdno4X289VND5kvRUeY+v/2u4bCTHkAf2UWtTHpEUu9mMzwceozQ=
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque

