---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: immich
spec:
  encryptedData:
    secret: AgCWDic5UO1MYMbdxM4VacZLncAo+hvDgKv66jRiyd3nbRs/MvwtPcIm4Xe7wu64wff4wrf8TfNANvKh/Ve8PglTAztYFrEZQV9bkd7nfKFp29O9AN6X/u42LcGrf1bIG76fFQySCgrlepOahX7ldM0oRe9aWsXLHr+8c0o9MmL9Wl0WDU4Zrqpiv5A+ezvRNobWi0pg2dUujDqD1rSgsAcXuzORDvW16Q/2QuWhg0l+Aie6KU9JnF/aAC70yZxJxoLJqvb+LEvSok/EcY/6nhdsnjDV+98r9GDQz79ns+LBxNz0o63Rch4gi1dTTmm1GDp7+8trwiVjovHXHbcfnhyixpMDkBRFi8rckzLfR+3coD9RdodGzhV4lTduPXV79nkl/XLyT+Rx/Qk4G8mbugF7kKB3rcuFeK2oA6y6EnuiNygTEVyddif1ev2AKbnsDyHURxTjpawL/y6HaWr13clHjbUu0y/WcOJMYMj/3FckIw52BN4kOZ58U1A49xvopwaibH9ygBTOrFk9g3ivlIrlZehfqBKvjTNm9qbk1+wq8vUKy9ud/ovqzrf8sF/Cl+xFpWYnNAnVl4fqy1FgO4H5yF71FEDryeVOYr9HdZaLL+1O3cij/xv+GzkEqNbGbKby+8Vyay6EX63XoGZWXUOmNBARQl+ycELxvtJ6a8qAuyGZJ/ANUw1QWbd9Nc8zlDYr5+4pLqrNSsmdy+LrGpT1LpX/Zc4avzQgBshRz3CLooUrnuI4GH4DfDJda7beNKKhjsVfhQfIwG1R4CuVlzdBe6GOs4zagZXT3kYK4UStcIM0UyInczn6YqWsv00hezEDxXRx6crxSiiU/38CqWDoZ6xUaBaJ3JOuAJ6mZsnzZECDZSmm4iFAtwrjNm6s/pPuUdOOYPk1amygHiu8L8XS6/UQLkDozwcyz5s3
  template:
    metadata:
      name: jwt-secret
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-creds
  namespace: immich
spec:
  encryptedData:
    password: AgAUKhBXsf/kEy3ENYV6phb62Nw3fUw674u4iFXFiKF0ziesoWsTnL6LAIFBCkNDiqCq9YnTharhKlFwN+StcAnqs9vKNDrJl+qEo9xSYwSBgAE5z7mlk35AqweDsZpT+/opqLG3vm+HLJ6QDs26Tjci6IiFV8TJdKhyK1m6KS26kq8oHfnT2kiqzlw/uACpORX+saaxm5A3C5qpHWri4ikvp4oqPSQF4nB+j+s0/g9wirhZyaLGv2ucmVFtEyRMibjvfDDQrYoMDmA6vagBd1AoftXyA/9EJhf1BQao+p6RuUzicN9mNTttLi4HNMoV+y6KQGpYm549T0rqKS9od69tDaBovSc/gK1BFKtCvmqvtAXgNP/MZh2WJGGc7E/eZgVMtCacUEQxGX3MgIc66avZBoSJKUaUvUWZN9DL0jFAJFi0U5g2lYmqMYakjg/vgH8poEAKV625QYs4za5cJg4RGWu2N8piXEFqvN09w2mRaduD2rPeXXfePA91gdZpiDWnHAzhs8sZGTPo7BumIdvn1ue+bng34lAwtGGuyowA1iV6FbNgacZ3I8eRkD1TjYFfZpR1xsa5b3RKvz3kbvWePUtiwgHyEBx/hzyVzxEVQ1DOUK2pNw0E1BKupEXdMVuaqQ29fcJN35KZDaWzvkGnrMCt1XDA6ucUmQlZwmG0xHjBJMiBVmILQd3ZAdEAr5Yg85AA3+tD1J3nYYI=
    username: AgCpaujkBzqNwP2TCAupcKe3dX0J4rC0np55kOgYkDb/Tldcn9FSzVULZYnn8dKRKaMf50l5okInXLfBex6j7fT5LP/a1iOPAO848DFZbLifANIEWXh0cbjgdEvwvNIeLMykliFHkrDG4iB+IZtNGpTOco6cbbccgnrPjc2tlhAobkhnC7JyzvdV2gew83e27d2emUx1Sm6kJcxBN8fs+tEK9TmyQNItHWTJp96QOXkoZr6Ti6Q8UlkjfkofYMvzMC12Jx0pNXiFHDqt9Sb6wUihBRccH792ref5k+PR6PM3BetySO3smQSTv0HoVNY0CmIHU7aVHRCXtah39krIx+dN2584IW+Guf+nzASeu86B0KdYcN5eleaoOT+fFvvISv1HKKvMePehEmsfuWbHJBsyhttObvKCNScLYw6+RBe6vh78pqRQdewAbt0NTv8cOoM41mRS6+t/SLK+hurbimk4Qpr1TZGI5q4hXG/fzvYIlXo+xzMkQKE8+v1VbTp5YIuxwFx5ySEGCESH8GoQBaUVf+KvSuAvNVQv4X9LoNkdB7UtD8NSEG0OHw3qmY4xyuglfnhZJaZSPaJFmPSLI4at2zMM89MHsuJlVWW04J5ph9hIyvtzR748Vi16ggtyKyDvI6tA1pxclBeiLVMzkCh7VVbzzcv5bW1t9iXQrN4TVmPqQSMqZszrSOiQbgesi2JD0+72OFM=
  template:
    metadata:
      name: postgres-creds
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-creds
  namespace: immich
spec:
  encryptedData:
    hostname: AgAZcXeaP1lB2Z98b6we9/x3FZJxGuND5Una2VmPc6LSkDZUp6OyzJqWIi70rQUBPSPUTvIgYRisW9xDur7Ud+7JV/qNLrDNPaDCRWRFiOhQ+aAScRH/lGhh8lJdPKzo2zOmfiR39mkVlCQ9UMfGb43pg6Mrg5D6xhelSfLCr30Ew4CGlq2MaT8ipCs2fnXozC2njPyydvwjYsgx218zSADxonQbMYmuR0F5zuOdHzaIjbmrvnhyBCaaAIAN7EHdom6fG2dS1deEasUMXUDUqOZsOiX1/MKW/HwaLXfLJe55gINTVCz2dgjUy3Yk4PbGZuWDQBekn4k7p+qLPPqjrLFhLbbyXQv89NruxetujW2p+LlxH+Bn0wfeVpVhakoG++B8Hr2F78xxYeoXXiVKWHIlMRhujmUyUn9gD54EDje81SLGM0Xm+HZDEumpPJlzSMBiNJAFCx6OG8/EU1gHtawtW4zDblJVCtQw05snDtslfNmJijCbNHaZAyD0HbGyk/7M+SwkQtwaV/r/Gyc2XzUs6/fkBTqXIjIlAqb5qZzejOpuXFZKGnKXwWC31XpTFeM2JSDHGyojliBoW7pzFiQBZb0aDpKTFiZ4+RCcpTlSRXDb389TmTPJhuZu64ZtbyoQOI9HbYhF4r8ssiZ1MUZrMtQZb08dmfPGxqOMha3xtjNbqN7+X+1mbvsEavX95lZd+5s4RDsKkRBirBBYmH2aU8tT1qY0gouL
    password: AgCwPU/O/KS65/QCejjQSajTcE/vtwaOz7FLMM/01q17308NZUG+WSCJC7p679wyLcuDLyCEyGtPbUSVIu9PBF+v9aWZ7ASzLSTkjJjtFi+eFi4kmGjBtfR3+O2qlSN28d4me1dFf9RkCp1xZFuCZc1yyDanhBQ2f1A8zmAOR7LxKp+6NQpKeip+RtejFbnF2pjy7rY1i8tN0Li600mJFxWi6gQXjzE1VAE+QMjsU2AOlczch41NYGJbFjlLu2g4MYa10LFx8w9aOHws5ynqQ88dOoPUlM91iTPOuOyaRc82HbT/S3LMBytHLYoRi8DjYAw7Q4aPlaHuBaQE5ttNLh9Jdmop9iUTXpZoAf1a3EeYq4tbhuwWdGwUIKp74hAAS8+c8ULTKULsMX3yVfTuOAa/UudHiqhA1QwcSVYdp7myq7mGsdaYf1C6zbvIKx/5p+z/hhJPYq4mzP3VvMWa6T0NASKxzd5Z3mqi8vK7ytPIkgwGGGrQufu7a1gTYXJn+JMX/GDz3g5mgmOxcpmZwl8ytpqYyper5QVHBbzYxaG1H1c60iodek7KP2tGZsJvRZ0VsFJNAgkHo8oyf9bvT8BDKAlcMW390QEw33pG5JScTBM5mEnZ8+NtrWDjxzzu218ThK2eaSgoRoO5qVxvBPKMYxsGU74F0v6kqeLkqaJQfKLH9y7W4CXF6oKFqi7sb41xSg/5Y1xs+sAAjCVj
  template:
    metadata:
      name: redis-creds
      namespace: immich
    type: Opaque
