apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-server
  namespace: immich
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
spec:
  rules:
  - host: photos.seymour.family
    http:
      paths:
      - backend:
          service:
            name: immich-server
            port:
              number: 3001
        path: /api
        pathType: Prefix
  tls:
  - hosts:
    - photos.seymour.family
    secretName: immich-tls
