---
# Source: matrix-bridges/templates/signal-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mautrix-telegram
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: mautrix-telegram
      containers:
        - name: mautrix-telegram
          image: dock.mau.dev/mautrix/telegram
          imagePullPolicy: IfNotPresent
          command:
            - python3
            - -m
            - mautrix_telegram
            - -c
            - /etc/telegram/config.yaml
          ports:
            - name: http
              containerPort: 29328
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_matrix/mau/live
              port: http
          readinessProbe:
            httpGet:
              path: /_matrix/mau/live
              port: http
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /etc/telegram
      volumes:
        - name: config
          secret:
            secretName: mautrix-telegram-config
