apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synapse
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - sealedsecret.yaml
  - images.yaml
commonLabels:
  app.kubernetes.io/name: mautrix-discord
  app.kubernetes.io/managed-by: kustomize
images:
  - name: dock.mau.dev/mautrix/discord
    newTag: v0.3.0 # {"$imagepolicy": "synapse:mautrix-discord:tag"}
