apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synapse
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - pvc.yaml
  - sealedsecret.yaml
  - images.yaml
commonLabels:
  app.kubernetes.io/component: mautrix-signal
images:
  - name: dock.mau.dev/mautrix/signal
    newTag: v0.5.0 # {"$imagepolicy": "synapse:mautrix-signal:tag"}
  - name: signald/signald
    newTag: 0.23.2 # {"$imagepolicy": "synapse:signald:tag"}
