apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgres
spec:
  interval: 1m
  chart:
    spec:
      chart: postgresql
      version: "11.9.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  valuesFiles:
    - values.yaml
