---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Gi
  iscsi:
    targetPortal: 192.168.1.100:3260
    iqn: iqn.2005-10.org.freenas.ctl:k3s-postgres
    lun: 0
    fsType: ext4
    chapAuthSession: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: manual
