apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBNv7wgy9u3AGRhZGAn0aXDmI3bfjIX67o1OHXQ4YlMG9deNWGVyovLPz23UzQ6K3GOxEJca6/6KNXaB7cTWmsBMJ5gfp8vHFwIlUy799kEkuJqyadCzYKKtMMAxSfZ561AkyO3ajQPDiwK9soPFunANLjikqvCj7c5TylW2DCmlRjmsboKLtwFVy0iIWSkwVuxhU7Ye5k1O9JHosV59R4hqt3q1VfdZZp/E+zq6it4oErn9cPhOJugNSHt7Fr2Ez8hMcq98THJNqSfdsVbmpeWDirDYAXis98zu/iFa+y9OFCW3GR+Sem1W/+JH+wdjPJ6ck7qJ/VHvK+eLF6VR9AD7yiEF1bLE6G3aTgaCKPzl9zfKAkJ96G6g+trTYGNJ8RTLPEup+9wbCjLvH0HNIQ612sw/r6pocIMoa44p8nDRrurbZJOZjVvp60zktyF2C67qaMFpQWPP5okiS/5bhvaGDgBlen2DkHTRT3B4xjB1ZtrGUpyxwdT1fh8uQhiw0INjWuI0eKCz7J9cxLhH/76ErVXkqDG6NKQM8Y9P+jq7mUVZdQyH/snct0Ykd3Z8git5JEkhkuo7tkzqQ0ztPQ+QS1gw5rbtrR8RINdJ9Agjv+ODtUhqLc/A5SrZnvi4HuI3j5WUQa9QxqFNkjeqOmqp2nbWTO81WiRW/81Q8irmE44SgqNeNBj446wszD44XlUpvTQ0E/BK2rnJKzOdm/YK9ovyLqG1KdzheGhmyCkz8yaPuSigVHP
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

