apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./master/application.yaml
  - ./master/service.yaml
  - configmap.yaml
  - headless-svc.yaml
  - health-configmap.yaml
  - scripts-configmap.yaml
  - sealedsecret.yaml
  - serviceaccount.yaml
