apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgBZl0AJCQEJK9w+/vysEeUJiS9KgQbck+yHswcaps7IoitvOPa19xExB9BmbKb/oZRgd75fCAGptYHHC15Mxn4HupB7TKXkgayNEoQHUsWu4JFbStc0Qpp6GPJsuLgYAkaj2yenFdycF4Tl5Q8RjgrHLrz+GCCtl5n+wp8yO3KZqyezG0+vCVBNXylI9/uD5ODj5n1YDHp0lXtdZtcgboIs1SQkPp4b5b9tE2lKG7vELpNV6W9xgt9kpYgOwDJ/RhBn4jhAVCaTpCjq99lgzqqvzCNTgAU0WiFvrUEKR7sYcxpcd0AH7+y2yzsOdH8IMvjXGo1qBFYh4D/RY/u+3PacpAlvryoMTAVen0PlNTCARzRyS9Xqg17IZHI5btO0CwKPQfGuSRrL8sD0rbqz3zDqxigEH9MOgA74X29XhkBw7wfSaImkXQ2REoEP15/7pdT2MWL1pIGKLT9y5w6+l+BG188+Lfz39o0yc47Jb6d6ENxHyGEnzyrdcXokOBeQScbfpns3Ib8XlNhwPUWr907wXo4ecTh1+Ya/7gDHjnMRPvXTpvVdc3hkQeouucuh64wJlQCAQALpdrfife+rss4zA2sioDoc2eo2sYNnWHCB8hojiWlkrY5cjRLpQkBj0LNNiLkI6UWDBs5EDl3tXokr2GHb2Cg2WqVvGWLe/Opt0SKmKu0MdkpNKnwWEmacN5AGCc+sQL5RVNA3xow=
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: redis
        app.kubernetes.io/name: redis
      name: redis
      namespace: redis
    type: Opaque
