name: Staging Auto-PR
on:
  push:
    branches: ["flux-image-updates"]

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: "main"
          pr_title: "[Flux] Image update"
          pr_body: "Flux would like to update a container image for you."
          pr_reviewer: "thefirstofthe300"
          github_token: ${{ secrets.GITHUB_TOKEN }}
